name: Auto Video Generator

on:
  schedule:
    - cron: '0 10 * * *'  # كل يوم الساعة 10 صباحًا UTC (حوالي 11 أو 12 ظهرًا بتوقيت الجزائر)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install moviepy
          pip install imageio imageio-ffmpeg
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
          pip install moviepy
      - name: Run video generator
        run: python generate_video.py
