name: Auto Video Generator

on:
  schedule:
    - cron: '0 10 * * *'  # يشغل كل يوم الساعة 10 صباحًا UTC
  workflow_dispatch:      # يسمح لك بتشغيله يدويًا من GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install moviepy
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run video generator
        run: python generate_video.py
